### ISSUE TITLE
Two instances caused potential memory release issues

### ISSUE THREAD

**Issue by Dwl2021** [NVlabs/curobo#509]
Environment:
1. cuRobo installation mode: python
2. python version: Python 3.10.0
3. Isaac Sim version (if using): not using

---

Main script:
```
# Third Party
import torch

# cuRobo
from curobo.types.math import Pose
from curobo.types.robot import JointState
from curobo.wrap.reacher.motion_gen import MotionGen, MotionGenConfig, MotionGenPlanConfig

world_config = {
    "cuboid": {
        "table": {
            "dims": [5.0, 5.0, 0.2],  # x, y, z
            "pose": [100.0, 0.0, -0.1, 1, 0, 0, 0.0],  # x, y, z, qw, qx, qy, qz
        },
    },
}

motion_gen_config = MotionGenConfig.load_from_robot_config(
    "/home/algo/dengweiliang/curobo_ws/scripts2/curobo1.yml",
    world_config,
    interpolation_dt=1/250,
    num_trajopt_seeds=1,
    num_graph_seeds=1
)
motion_gen = MotionGen(motion_gen_config)
motion_gen.warmup(batch=10)

''' motion_gen2 instantiation
motion_gen_config2 = MotionGenConfig.load_from_robot_config(
    "/home/algo/dengweiliang/curobo_ws/scripts2/curobo2.yml",
    world_config,
    interpolation_dt=1/250,
    num_trajopt_seeds=1,
    num_graph_seeds=1
)
motion_gen2 = MotionGen(motion_gen_config2)
motion_gen2.warmup(batch=10)
'''

tensor = torch.tensor([[ 0.5575, -0.3169, -0.0265,  0.0615, -0.0013, -0.7093,  0.7022],
        [ 0.5584, -0.2949, -0.0262,  0.0260,  0.0338, -0.7115,  0.7014],
        [ 0.5570, -0.2729, -0.0258,  0.0096, -0.0688,  0.7119, -0.6988],
        [ 0.5535, -0.2512, -0.0252,  0.0452, -0.1037,  0.7106, -0.6945],
        [ 0.5479, -0.2300, -0.0244,  0.0806, -0.1383,  0.7074, -0.6884],
        [ 0.5402, -0.2094, -0.0235,  0.1159, -0.1725,  0.7025, -0.6807],
        [ 0.5304, -0.1897, -0.0224,  0.1508, -0.2063,  0.6958, -0.6712],
        [ 0.5188, -0.1711, -0.0211,  0.1854, -0.2396,  0.6874, -0.6600],
        [ 0.5053, -0.1538, -0.0198,  0.2196, -0.2723,  0.6773, -0.6472],
        [ 0.4902, -0.1379, -0.0183,  0.2531, -0.3043,  0.6655, -0.6328]])
tensor = tensor.cuda()
goal_pose_of_gripper = Pose(tensor[:, :3], tensor[:, 3:])
joint_angles = [0.0, -0.0, 0.0, 0.0, -0.0, 0.0]
joint_angles_cuda = torch.tensor(joint_angles, dtype=torch.float32).cuda().reshape(1, -1)
joint_angles_cuda = torch.cat([joint_angles_cuda] * 10, dim=0)
start_joint_states = JointState.from_position(
    joint_angles_cuda,
    joint_names=['fl_joint1', 'fl_joint2', 'fl_joint3', 'fl_joint4', 'fl_joint5', 'fl_joint6']
)
plan_config = MotionGenPlanConfig(max_attempts=10)
result = motion_gen.plan_batch(
                start_joint_states, 
                goal_pose_of_gripper, 
                plan_config
            )
```

The above script executes successfully as written. However, if I uncomment the `motion_gen2 instantiation` section, the script throws an error. I believe this occurs because multiple instances are sharing the same low-level components, and initializing additional instances resets certain variables, causing memory address misalignment.

The error is as follows:
```
(dwl2) algo@BCE-RTX4090-48G:~/dengweiliang/curobo_ws/scripts2$ python3 minimal.py 
Batch mode enable graph is only supported with num_graph_seeds==1
Batch mode enable graph is only supported with num_graph_seeds==1
Batch mode enable graph is only supported with num_graph_seeds==1
Batch mode enable graph is only supported with num_graph_seeds==1
Batch mode enable graph is only supported with num_graph_seeds==1
Batch mode enable graph is only supported with num_graph_seeds==1
Batch mode enable graph is only supported with num_graph_seeds==1
Traceback (most recent call last):
  File "/home/algo/dengweiliang/curobo_ws/scripts2/minimal.py", line 58, in <module>
    result = motion_gen.plan_batch(
  File "/home/algo/dengweiliang/curobo/src/curobo/wrap/reacher/motion_gen.py", line 1649, in plan_batch
    result = self._plan_batch_attempts(
  File "/home/algo/dengweiliang/curobo/src/curobo/wrap/reacher/motion_gen.py", line 3194, in _plan_batch_attempts
    result = self._plan_from_solve_state_batch(
  File "/home/algo/dengweiliang/curobo/src/curobo/wrap/reacher/motion_gen.py", line 3859, in _plan_from_solve_state_batch
    ik_result = self._solve_ik_from_solve_state(
  File "/home/algo/miniconda3/envs/dwl2/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/algo/dengweiliang/curobo/src/curobo/wrap/reacher/motion_gen.py", line 2820, in _solve_ik_from_solve_state
    ik_result = self.ik_solver.solve_any(
  File "/home/algo/dengweiliang/curobo/src/curobo/wrap/reacher/ik_solver.py", line 1211, in solve_any
    return self.solve_batch(
  File "/home/algo/dengweiliang/curobo/src/curobo/wrap/reacher/ik_solver.py", line 823, in solve_batch
    return self._solve_from_solve_state(
  File "/home/algo/dengweiliang/curobo/src/curobo/wrap/reacher/ik_solver.py", line 1077, in _solve_from_solve_state
    ik_result = self._get_result(num_seeds, result, goal_buffer.goal_pose, return_seeds)
  File "/home/algo/miniconda3/envs/dwl2/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/algo/dengweiliang/curobo/src/curobo/wrap/reacher/ik_solver.py", line 1104, in _get_result
    q_sol, success, position_error, rotation_error, total_error, goalset_index = get_result(
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/algo/dengweiliang/curobo/src/curobo/wrap/reacher/ik_solver.py", line 1647, in get_result
    """JIT compatible function to get the best IK solutions."""
    error = pose_error.view(-1, num_seeds)
    error[~success] += 1000.0
    ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _, idx = torch.topk(error, k=return_seeds, largest=False, dim=-1)
    idx = idx + num_seeds * col.unsqueeze(-1)
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
```

---

To help you solve this quickly, I've compressed and uploaded the workspace [scripts.zip](https://github.com/user-attachments/files/20220186/scripts.zip). You'll need to modify some absolute paths in `curobo1.yml`, `curobo2.yml` and `minimal.py`.

**Comment by balakumar-s** [comment]
We have solved this issue in our most recent release (v0.8.0). The issue happens when a previous cuda graph capture is not garbage collected.
