### ISSUE TITLE
CUDA compatibility issue with RTX 5070 Ti - "no kernel image is available for execution on the device"

### ISSUE THREAD

**Issue by xxwxxs** [NVlabs/curobo#578]
Description

I'm encountering a CUDA kernel compatibility issue when using cuRobo with my NVIDIA GeForce RTX 5070 Ti GPU. The error occurs during the initialization of CUDA kernels and prevents the library from functioning properly.

Environment

    GPU: NVIDIA GeForce RTX 5070 Ti 

    Driver Version: 570.181

    CUDA Version: 12.8

    OS: Ubuntu 22.04

    Python Version: 3.12.12

Error Log
Traceback (most recent call last):
  File "/home/xxw/curobo/examples/collision_check_example.py", line 40, in <module>
    config = RobotWorldConfig.load_from_config(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxw/curobo/src/curobo/wrap/model/robot_world.py", line 80, in load_from_config
    robot_config = RobotConfig.from_dict(robot_config, tensor_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxw/curobo/src/curobo/types/robot.py", line 50, in from_dict
    data_dict["kinematics"] = CudaRobotModelConfig.from_config(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxw/curobo/src/curobo/cuda_robot_model/cuda_robot_model.py", line 248, in from_config
    generator = CudaRobotGenerator(config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxw/curobo/src/curobo/cuda_robot_model/cuda_robot_generator.py", line 260, in __init__
    self.initialize_tensors()
  File "/home/xxw/miniconda3/envs/h2/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/xxw/curobo/src/curobo/cuda_robot_model/cuda_robot_generator.py", line 337, in initialize_tensors
    self._build_kinematics_with_lock_joints(
  File "/home/xxw/miniconda3/envs/h2/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/xxw/curobo/src/curobo/cuda_robot_model/cuda_robot_generator.py", line 673, in _build_kinematics_with_lock_joints
    link_poses = self._get_link_poses(q, lock_links, kinematics_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxw/miniconda3/envs/h2/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/xxw/curobo/src/curobo/cuda_robot_model/cuda_robot_generator.py", line 1072, in _get_link_poses
    link_pos_seq, link_quat_seq, _ = get_cuda_kinematics(
                                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/xxw/curobo/src/curobo/curobolib/kinematics.py", line 250, in get_cuda_kinematics
    link_pos, link_quat, robot_spheres = KinematicsFusedFunction.apply(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxw/miniconda3/envs/h2/lib/python3.12/site-packages/torch/autograd/function.py", line 582, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxw/curobo/src/curobo/curobolib/kinematics.py", line 73, in forward
    r = kinematics_fused_cu.forward(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device
Search for `cudaErrorNoKernelImageForDevice' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Steps to Reproduce

    Install cuRobo according to the official documentation

    Run any example that uses CUDA kernels (e.g., collision_check_example.py)

    The error occurs during CUDA kernel initialization

------
Issue Details

**Comment by patrick-deschambault** [comment]
Got also a similar issue. I am using a RTX5080 and I am facing the same symptoms.

**Comment by xxwxxs** [comment]
> 也遇到了类似的问题。我正在使用RTX5080,并且我面临着同样的症状。

We are not facing the problem now, but we have found a solution for the architecture issue. After adjusting the versions of CUDA and PyTorch in the virtual environment, it can adapt to the 50-series graphics card architecture. For your reference: in a conda virtual environment with Python 3.10, I used:

pip install torch==2.7.1 torchvision==0.22.1 torchaudio==2.7.1 --index-url https://download.pytorch.org/whl/cu128

This version is diversified. Similarly, 2.9.0+cu128 and 2.8.0+cu128 are also acceptable. Hope this helps you solve the problem.

**Comment by dibbla** [comment]
Also found the issue on H200s.

**Comment by balakumar-s** [comment]
We have moved to using nvrtc for compilation with CUDA python, this should support H200 and blackwell without requiring additional environment variables.
